import './globals.scss';
import type { Metadata } from 'next';
import { JetBrains_Mono, Geist_Mono } from 'next/font/google';
import Header from './components/header/Header';
import 'bootstrap/dist/css/bootstrap.min.css';
import Script from 'next/script';

const geistSans = JetBrains_Mono  ({
  subsets: ['latin'],
  weight: ['400'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'my-app-weather',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${geistSans.className} ${geistMono.variable}`}>
        <Header />
        {children}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
